### ISSUE TITLE
Test camera with board ESP32-S2-kaluga-1 V1.2, Occasionally an abnormal picture

### ISSUE THREAD

**Issue by YanMinge** [espressif/esp-dev-kits#19]
【Test environment】
1. ESP32-S2-Kaluga-1 V1.2
2. ESP-LyraP-CAM V1.0
3. ESP-LyraP-LCD32 V1.1

【Software configuration】
1. camera pad type ->  ESP32-S2-KALUGA V1.2
2. LCD pad type -> ESP32-S2-KALUGA V1.2
3. Camera version -> OV2640
4. LCD version -> ILI9341
5. enable jpeg mode

【LCD screenshot】
![Screenshot](https://user-images.githubusercontent.com/5819541/93752823-c6f89b80-fc31-11ea-859d-d4645c8317db.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/5819541/93753163-48e8c480-fc32-11ea-8439-ffd6b83213df.jpg)

【Probability of occurrence】
It can appear 3-5 times a minute

I don’t know if this is a defect in my hardware or there have bugs in software. I hope to get your reply.
and the software here is not same as https://github.com/espressif/esp32-camera， Which camera driver will be more stable? Have you considered merging into the same design?

**Comment by felmue** [comment]
Hi @YanMinge 

FWIW: I do have the exact same ESP32-S2-kaluga-1 v1.2 board with the same camera v1.0 and same LCD v1.1 and I get the exact same abnormal picture occasionally.

BTW: When I disable JPEG mode I don't see the issue. This makes me believe that either the JPEG data from the camera is corrupt from time to time or the JPEG decoder fails to properly decode the data from time to time.

Also when I cover the camera (which results in a black image) I don't see the abnormal image. So maybe the issue lies with the complexity of the JPEG image?

Felix
